<footer id="footer">
	<div class="container-fluid clearfix" >
		<div class="pull-left text-center">Exercice Blog - 3WA</div>
		<div class="pull-left text-center">
			<ul>
				<li><a href="#"><i class="fa fa-facebook-square"></i></a></li>
				<li><a href="#"><i class="fa fa-twitter-square"></i></a></li>
				<li><a href="#"><i class="fa fa-linkedin-square"></i></a></li>
			</ul>
		</div>
		
		<div class="pull-left text-center">
			<p>Thomas - Stéphane - Mick - Marlone</p>
		</div>
	</div>
</footer>
