<nav class="container-header">
	<div class="header clearfix">
		<img class="logo-header text-center" src="public/images/logo.png" alt="Logo">
	</div>
	<ul class="header-nav clearfix">
		<li class="text-center"><a href="index.php?page=home">MEN</a></li>
		<li class="text-center"><a href="index.php?page=logout">ACCESSORIES</a></li>
		<li class="text-center"><a href="index.php?page=logout">WOMEN</a></li>
	</ul>
	<ul class="header-icon clearfix">
		<li class="pull-right icon"><a href="index.php?page=logout" title="Logout"><i class="fa fa-times"></i></a></li>
		<li class="pull-right icon"><a href="index.php?page=profile_admin" title="My account"><i class="fa fa-user"></i></a></li>
	</ul>
	<ul class="header-icon clearfix">
		<li class="pull-right icon"><a href="index.php?page=current_cart" title="Cart"><i class="fa fa-shopping-cart"></i></a></li>
		<li class="pull-right icon"><a href="index.php?page=search" title="Search"><i class="fa fa-search"></i></a></li>
	</ul>
</nav>