<nav class="container-header">
	<div class="header">
		<img class="logo-header" src="public/images/logo-campshop-01.png" alt="Logo">
	</div>
	<ul class="header-nav">
		<li class="text-center"><a href="index.php?page=home">MEN</a></li>
		<li class="text-center"><a href="index.php?page=logout">ACCESSORIES</a></li>
		<li class="text-center"><a href="index.php?page=logout">WOMEN</a></li>
	</ul>
	<ul class="header-icon">
		<li class="pull-right icon"><a href="index.php?page=logout"><i class="fa fa-user"></i></a></li>
		<li class="pull-right icon"><a href="index.php?page=logout"><i class="fa fa-shopping-cart"></i></a></li>
		<li class="pull-right icon"><a href="index.php?page=logout"><i class="fa fa-search"></i></a></li>
	</ul>
</nav>