<div class="wrapper">
	<header class="header-wrapper">
		<nav class="container-header">
			<div class="header clearfix">
				<a href="index.php?page=home"><img class="logo-header text-center" src="public/images/logo.png" alt="Logo"></a>
			</div>

			<ul class="header-nav clearfix">
				<div class="hover">
				<li class="text-center"><a href="index.php?page=shop&id_cat=2">MEN</a></li>
				</div>
				<li class="text-center"><a href="index.php?page=shop&id_cat=1">ACCESSORIES</a></li>
				<li class="text-center"><a href="index.php?page=shop&id_cat=3">WOMEN</a></li>
			</ul>

			<ul class="header-icon clearfix">
				<li class="pull-right icon"><a href="index.php?page=logout" title="Logout"><i class="fa fa-times"></i></a></li>
				<li class="pull-right icon"><a href="index.php?page=profile" title="My account"><i class="fa fa-user"></i></a></li>
			</ul>
			
			<ul class="header-icon clearfix">
				<li class="pull-right icon"><a href="index.php?page=current_cart" title="Cart"><i class="fa fa-shopping-cart"></i></a></li>
				<li class="pull-right icon"><a href="index.php?page=search" title="Search"><i class="fa fa-search"></i></a></li>
			</ul>
		</nav>
	</header>
