<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Model-HTML/CSS</title>

    <!-- Bootstrap -->
    <link href="public/styles/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet/less" type="text/css" href="public/styles/style.less" />

    <script src="public/scripts/jquery-2.2.3.min.js"></script>
    <script src="public/scripts/bootstrap.min.js"></script>
    <script type="text/javascript" src="public/scripts/less.min.js"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    
    <?php
      require 'apps/header.php';
      require 'apps/content.php';
      require 'apps/footer.php';
    ?>


  </body>
</html>