<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Campshop</title>

    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Raleway:300,500,600,,700,800' rel='stylesheet' type='text/css'>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <!-- Bootstrap -->
    <link href="public/styles/bootstrap.min.css" rel="stylesheet">

    <!-- Style -->
    <link rel="stylesheet" type="text/css" href="public/styles/reset.css" />
    <link rel="stylesheet/less" type="text/css" href="public/styles/style.less" />

    <!-- Owl Carousel CSS -->
    <link rel="stylesheet" href="public/styles/owl.carousel.min.css">


    <!-- Owl Caroussel JS -->
    <script src="public/scripts/jquery-2.2.3.min.js"></script>
    <script src="public/scripts/owl.carousel.min.js"></script>
    <script src="public/scripts/owl.init.js"></script>

    <!-- Bootstrap JS -->
    <script src="public/scripts/bootstrap.min.js"></script>

    <!-- Menu Burger -->
    <script src="public/scripts/menu_burger.js"></script>

    
    <!-- Less JS -->
    <script type="text/javascript" src="public/scripts/less.min.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>

  <body>
    <?php
        require 'apps/header.php';
        require 'apps/content.php';
        require 'apps/footer.php';
    ?>
  </body>
</html>