<div class="text-center">
	<h2 class="title"><?=$action?> Sub-Category</h2>
	<div>
		<?=$error?>
	</div>
	
	<form class="edit-subCategory" method="POST" action="index.php?page=add_edit_subcat">
		<div class="clearfix edit-subCategory-fields">
			<label for="category" >Category</label>
			<select class="input" name="id_category" id="category">
				<?php require 'apps/contents/category_option.php';?>
			</select>
		</div>

		<div class="clearfix edit-subCategory-fields">
			<label for="name">Name</label>
			<input class="input" type="text" name="name" id="name" placeholder="<?=$name?>" value="<?=$nameEdit?>" />
		</div>

		<div class="clearfix edit-subCategory-fields">
			<label for="description">Description</label>
			<textarea class="input" name="description" id="description" cols="30" rows="10" placeholder="<?=$description?>"><?=$descriptionEdit?></textarea>
		</div>
		
		<input type="hidden" name="action" value="<?=$action?>">
		<input type="hidden" name="id_sub_cat" value="<?=$id_sub_cat?>"/>
		<input class="valid-button" type="submit" />
	</form>
</div>