<div id="edit_address" class="edit-address">

	<h1 class="title text-center"><?=$action?> ADDRESS</h1>
	<?=$error?>

	<form class="form-style" method="POST" action="index.php?page=address">

		<div class="form-group clearfix">
			<label for="name">Name</label>
			<input type="text" name="name" autofocus class="input" id="name" placeholder="<?=$name?>" value="<?=$nameEdit?>">
		</div>

		<div class="form-group clearfix">
			<label for="number">Number</label>
			<input type="text" name="number" class="input" id="number" placeholder="<?=$number?>" value="<?=$numberEdit?>">
		</div>

		<div class="form-group clearfix">
			<label for="pathway">Pathway</label>
			<input type="text" name="pathway" class="input" id="pathway" placeholder="<?=$pathway?>" value="<?=$pathwayEdit?>">
		</div>

		<div class="form-group clearfix">
			<label for="city">City</label>
			<input type="text" name="city" autofocus class="input" id="city" placeholder="<?=$city?>" value="<?=$cityEdit?>">
		</div>

		<div class="form-group clearfix">
			<label for="country">Country</label>
			<input type="text" name="country" autofocus class="input" id="country" placeholder="<?=$country?>" value="<?=$countryEdit?>">
		</div>

		<div class="form-group clearfix">
			<label for="zipcode">Zipcode</label>
			<input type="text" name="zipcode" class="input" id="zipcode" placeholder="<?=$zipcode?>" value="<?=$zipcodeEdit?>">
		</div>

		<div class="address-type clearfix">
			<p>Address type :</p>

			<div class="pull-left radio form-group clearfix">
				<input type="radio" name="type" value="0" id="home" <?=$home?> /><label class="radio" for="home">Home</label>
			</div>

			<div class="pull-left radio form-group clearfix">
				<input type="radio" name="type" value="1" id="work" <?=$work?> /><label class="radio" for="work">Work</label>
			</div>
		</div>
		
		<input type="hidden" name="action" value="<?=$action?>" />
		<input type="hidden" name="id_address" value="<?=$id_address?>">
		<input type="hidden" name="form" value="1">

		<div class="edit-valid-button text-center"><input class="valid-button" type="submit" value="Valider"></div>
	</form>
</div>