<div id="cat_admin" class="category-manager-container">
	<h2 class="text-center">Edit Category</h2>

	<div class="error">
		<?=$error?>
	</div>

	<div class="success">
		<?=$success?>
	</div>
	
	<div class="category-manager-content">
		<div class="category-add-button ">
			<!--<a class="valid-button" href="index.php?page=add_edit_cat">Add Category</a> -> pas opérationnel -->
			<a class="valid-button" href="index.php?page=add_edit_sub_cat">Add Sub-Category</a>
		</div>

		<div class="display-category-manager">
			<ul>
				<?php require 'apps/contents/display_cat.php';?>
			</ul>
		</div>
	</div>
</div>