<div class="category-manager-container">
	<h1 class="text-center title">Category Manager</h1>

	<div class="error">
		<?=$error?>
	</div>
	
	<div id="cat_admin" class="category-manager-content">
		<div class="category-add-button ">
			<a class="valid-button" href="index.php?page=add_edit_cat">Add Category</a>
			<a class="valid-button" href="index.php?page=add_edit_sub_cat">Add Sub-Category</a>
		</div>

		<div class="display-category-manager">
			<ul>
				<?php require 'apps/contents/display_cat.php';?>
			</ul>
		</div>
	</div>
</div>