<div class="edit-password">
	<h1 class="text-center">Change My Password</h1>

	<form class="form-style" method="POST">
		<div class="form-group clearfix">
			<label for="password">New Password</label>
			<input type="password" name="password" class="input" id="password">
		</div>
		<div class="form-group clearfix">
			<label for="confirmPassword">Confirm Password</label>
			<input type="password" name="confirmPassword" class="input" id="confirmPassword">
		</div>

		<input type="hidden" name="action" value="pass_change" />
		
		<div class="edit-valid-button text-center"><input class="valid-button" type="submit" value="Valider"></div>
	</form>
</div>