<div id="delete">
	<form action="index.php?page=edit_contact" method="POST">
		<div>Do You really want to delete your account :  </div>
		<input type="radio" name="choice" id="yes" value="yes"><label for="yes">Yes</label>
		<input type="radio" name="choice" id="no" value="no" checked><label for="no">No</label>
		<input type="hidden" name="action" value="delete">
		<input type="submit" value="Submit">
	</form>	
</div>