<div class="cart text-center">
	<h2 class="text-center">Your Cart Content</h2>
	<div class="error">
		<?=$error?>
	</div>

	<div class="success">
		<?=$success?>
	</div>

	<table class="cart-content text-left">
		<thead>
			<tr>
				<th>Product</th>
				<th>Size</th>
				<th>Quantity</th>
				<th colspan="3">Price</th>
				<th></th>
			</tr>
		</thead>

		<tbody>
			<?php 
				require 'apps/contents/form_current_cart.php';
			?>
		</tbody>

		<tfoot>
			<tr>
				<td colspan="3">Total</td>
				<td colspan="2"><?=htmlentities($cart->getPrice())?></td>
			</tr>
		</tfoot>
	</table>

	<form class="cart-content form-style clearfix" method="POST" action="index.php?page=current_cart">
		<input type="hidden" name="action" value="valid">
		<input type="hidden" name="id_cart" value="<?=$cart->getId()?>">
		<input class="checkout pull-right" type="submit" value="Check Out">
	</form>
</div>