<div class="cart text-center">
	<h2 class="text-center">Your Cart Content</h2>
	<?=$error?>
	<table class="cart-content text-left">
		<thead>
			<tr>
				<th>Product</th>
				<th>Size</th>
				<th>Quantity</th>
				<th colspan="3">Price</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<tr class="cart-content">
				<td>blah blah blah</td>
				<td>blah blah blah</td>
				<td>blah blah blah</td>
				<td>blah blah blah</td>
				<td>blah blah blah</td>
			</tr>
			<?php 
				require 'apps/contents/form_current_cart.php';
			?>
		</tbody>
		<tfoot>
			<tr class="total">
				<td  colspan="3">Total</td>
				<td colspan="2"><?=$cart->getPrice()?></td>
				<td></td>
			</tr>
		</tfoot>
	</table>
	<form class="cart-content" method="POST" action="index.php?page=cart">
		<input type="hidden" name="action" value="valid">
		<input type="hidden" name="id_cart" value="<?=$cart->getId()?>">
		<input class="checkout pull-right" type="submit" value="Check Out">
	</form>
</div>