<div class="grid-products col-lg-4">
	<div class="menu-burger-container clearfix">
		<?php require "apps/contents/menu_burger.php"; ?>
	</div>

	<div class="pict-products">
		<img class="picture" src="<?=$products[$i]->getPicture()?>" alt="prod_pic">
	</div>

	<div class="info-products">
		<h3><?=$products[$i]->getName()?></h3>
		<p><?=$products[$i]->getPrice()?></p>
		<div class="see-products">
			<a href="index.php?page=product&id_product=<?=$products[$i]->getId()?>">See Product</a>
		</div>
	</div>
</div>