<div class="feedback-content">
	<div class="feedback-header feedback-container">
		<div>
			<p><?=$user->getLogin()?></p>
			<p><?=$product->getName()?></p>
		</div>
		<div>
			<?=$feedbacks[$i]->getdate()?>
		</div>
	</div>
	<div class="feedback-content">
		<?=$feedbacks[$i]->getContent()?>
	</div>
	<div class="feedback-menu clearfix feedback-content">
		<form class="feedback-moderation-button pull-left" method="POST">
			<input type="hidden" name="action" value="valid">
			<input type="hidden" name="id_feedback" value="<?=$feedbacks[$i]->getId()?>">
			<input type="submit" value="Valid">
		</form>
		<form class="feedback-moderation-button pull-left" method="POST">
			<input type="hidden" name="id_feedback" value="<?=$feedbacks[$i]->getId()?>">
			<input type="hidden" name="action" value="refuse">
			<input type="submit" value="Refuse">
		</form>
	</div>
</div>