<li class="col-sm-4 col-md-6 col-lg-6">
	<div class="subCategory-name clearfix row"><?=$subCategories[$j]->getName();?></div>
	
	
		<form  class="subCategory-manager-button col-sm-4 col-md-6 col-lg-6" method="POST" action="index.php?page=add_edit_sub_cat">
			<input type="hidden" name="action" value="edit">
			<input type="hidden" name="id_sub_cat" value="<?=$subCategories[$i]->getId()?>">
			<input type="hidden" name="form" value="1">
			<input type="submit" value="edit">
		</form>
		<form  class="subCategory-manager-button col-sm-4 col-md-6 col-lg-6" method="POST" action="index.php?page=cat_admin">
			<input type="hidden" name="action" value="delete">
			<input type="hidden" name="id_sub_cat" value="<?=$subCategories[$i]->getId()?>">
			<input type="submit" value="delete">
		</form>
	
</li>