<div class="feedback-container <?=$refuse?> <?=$waitinglist?>">
	<div class="feeback-header">
		<div>
			<?=$product->getName()?>
		</div>
		<div>
			<?=$feedbacks[$i]->getdate()?>
		</div>
	</div>
	<div class="feedback-content">
		<?=$feedbacks[$i]->getContent()?>
	</div>
	<div class="feedback-menu">
		<form method="POST" action="index.php?page=add_edit_feedback">
			<input type="hidden" name="action" value="edit">
			<input type="hidden" name="id_feedback" value="<?=$feedbacks[$i]->getId()?>">
			<input type="hidden" name="form" value="1">
			<input type="submit" value="Edit">
		</form>
		<form method="POST">
			<input type="hidden" name="id_feedback" value="<?=$feedbacks[$i]->getId()?>">
			<input type="hidden" name="action" value="delete">
			<input type="submit" value="Delete">
		</form>
	</div>
</div>