<div class="feedback-container <?=$refuse?> <?=$waitinglist?>">
	<div class="feeback-header">
		<div>
			<?=$product->getName()?>
		</div>
		<div>
			<?=$feedbacks[$i]->getdate()?>
		</div>
	</div>
	<div class="feedback-content">
		<?=$feedbacks[$i]->getContent()?>
	</div>
	<div class="feedback-menu">
		<ul>
			<li><a href="index.php?page=add_edit_feedback&id=<?=$feedbacks[$i]->getId()?>">Edit</a></li>
			<li><a href="index.php?page=feedback&action=delete&id=<?=$feedbacks[$i]->getId()?>">Delete</a></li>
		</ul>
	</div>
</div>