<div class="feedback-container">
	<div class="feeback-header">
		<div>
			<p><?=$user->getLogin()?></p>
			<p><?=$product->getName()?></p>
		</div>
		<div>
			<?=$feedbacks[$i]->getdate()?>
		</div>
	</div>
	<div class="feedback-content">
		<?=$feedbacks[$i]->getContent()?>
	</div>
	<div class="feedback-menu">
		<ul>
			<li><a href="index.php?page=feedback&action=valid&id=<?=$feedbacks[$i]->getId()?>">Validate</a></li>
			<li><a href="index.php?page=feedback&action=refuse&id=<?=$feedbacks[$i]->getId()?>">Refuse</a></li>
		</ul>
	</div>
</div>