<tr>
	<td>
		<div><?=htmlentities($products[$i]->getName())?></div>
		<img class="cart-picture" src="<?=htmlentities($products[$i]->getPicture())?>" alt="img product">
	</td>

	<td>
		<?=htmlentities($products[$i]->getSize())?>
	</td>
	<td>
		<?=$quantity?>
	</td>
	<td>
		<?=htmlentities($products[$i]->getPrice())?>
	</td>
	
	<td class="clearfix">
		<form class="cart-remove-product pull-right" method="POST" action="index.php?page=current_cart">
			<input type="hidden" name="id_product" value="<?=$products[$i]->getId()?>">
			<input type="hidden" name="quantity" value="<?=$quantity?>">
			<input type="hidden" name="action" value="removeProduct">
			<input type="submit" value="remove">
		</form>
	</td>
</tr>