<form method="POST">
	<div class="product-size">
		<label for="size">Size</label>
		<select name="size" id="size">
			<option value="S">S</option>
			<option value="M" selected>M</option>
			<option value="L">L</option>
		</select>
	</div>
	<div class="product-quantity">
		<label for="quantity">Quantity</label>
		<input class="input" type="number" name ="quantity" min="1" max="<?=$max?>" />
	</div>
	<input type="hidden" name="action" value="addProduct">
	<div class="text-center"><input class="valid-button" type="submit" value="Valider"></div>
</form>