<form method="POST" action="index.php?page=product&id_product=<?=$id_product?>">
	<div class="product-quantity">
		<label for="quantity">Quantity</label>
		<input class="input" type="number" name ="quantity" min="1" max="<?=$max?>" />
	</div>

	<input type="hidden" name="action" value="addProduct">
	<input type="hidden" name="size" value="0">
	<input type="hidden" name="id_product" value="<?=$id_product?>">
	<input class="valid-button pull-right" type="submit" value="Valider">
</form>