<div class="container-fluid home-intro">
	<div class="home-intro-content">
		<video loop muted class="video-home" src="./public/video/video_eshop.webm">
		</video>
	</div>

	<div class="home-content">
		<div class="rubriques text-center">
			<div class="men pull-left clearfix">
				<a href="index.php?page=men"> MEN </a>	
			</div>
			<div class="accessories pull-left clearfix">
				<a href="index.php?page=accessories"> ACCESSORIES </a>	
			</div>
			<div class="women pull-left clearfix">
				<a href="index.php?page=women"> WOMEN </a>	
			</div>
		</div>

		<div class="presentation">
			<img src="./public/images/webelieve.jpg" alt="">	
		</div>

		<div class="news text-center clearfix">
			<h1><i class="fa fa-chevron-down"></i> WHAT'S NEW <i class="fa fa-chevron-down"></i></h1>
			<div class="owl-carousel owl-theme">
				<div><a href="index.php?page=men"><img src="./public/images/products/accessories/glasses/shelter.png"></a></div>
				<div><a href="index.php?page=men"><img src="./public/images/products/men/jackets/hemlock.jpg"></a></div>
				<div><a href="index.php?page=men"><img src="./public/images/products/accessories/bags/little_america_beige.jpeg"></a></div>
				<div><a href="index.php?page=men"><img src="./public/images/products/accessories/glasses/shelter.png"></a></div>
				<div><a href="index.php?page=men"><img src="./public/images/products/men/jackets/hemlock.jpg"></a></div>
				<div><a href="index.php?page=men"><img src="./public/images/products/accessories/bags/little_america_beige.jpeg"></a></div>
			</div>
		</div>
	</div>
</div>