<div class="container-fluid home-intro">
	<div class="home-intro-content">
		<video  loop muted class="video-home" src="./public/video/video_eshop.webm">
		</video>
	</div>

	<div class="home-content">
		<div class="rubriques text-center">
			<div class="men pull-left clearfix">
				<a href="index.php?page=shop&id_cat=2"> MEN </a>	
			</div>

			<div class="accessories pull-left clearfix">
				<a href="index.php?page=shop&id_cat=1"> ACCESSORIES </a>	
			</div>

			<div class="women pull-left clearfix">
				<a href="index.php?page=shop&id_cat=3"> WOMEN </a>	
			</div>
		</div>

		<div class="presentation">
			<img src="./public/images/webelieve.jpg" alt="">	
		</div>

		<div class="news text-center clearfix row">
			<h1>
				<i class="fa fa-chevron-down">	
					</i> WHAT'S NEW <i class="fa fa-chevron-down">
				</i>
			</h1>
		</div>

		<div class="owl-carousel row">
			<div class="owl-item">
				<img src="public/images/slider/slide-1.jpg" alt="image-slider">
			</div>

			<div class="owl-item">
				<img src="public/images/slider/slide-2.jpg" alt="image-slider">
			</div>

			<div class="owl-item">
				<img src="public/images/slider/slide-3.jpg" alt="image-slider">
			</div>

			<div class="owl-item">
				<img src="public/images/slider/slide-4.jpg" alt="image-slider">
			</div>

			<div class="owl-item">
				<img src="public/images/slider/slide-5.jpg" alt="image-slider">
			</div>

			<div class="owl-item">
				<img src="public/images/slider/slide-6.jpg" alt="image-slider">
			</div>

			<div class="owl-item">
				<img src="public/images/slider/slide-7.jpg" alt="image-slider">
			</div>

			<div class="owl-item">
				<img src="public/images/slider/slide-8.jpg" alt="image-slider">
			</div>
		</div>
	</div>
</div>