<div class="container-fluid">
	<video loop muted class="video-home">
	 	<source src="./public/video/video_eshop.webm">
	</video>

	<div class="rubriques text-center clearfix">
		<div class="men pull-left">
			<a href="index.php?page=men"> MEN </a>	
		</div>
		<div class="accessories pull-left">
			<a href="index.php?page=men"> ACCESSORIES </a>	
		</div>
		<div class="women pull-left">
			<a href="index.php?page=men"> WOMEN </a>	
		</div>
	</div>

</div>