<h1>Login</h1>

<form method = "POST" class = "form-logreg">

	<div class = "form-log">
		<label for="email">Email address</label>
		<input type="email" name="email" id="email" placeholder="your email">
	</div>

	<div class = "form-log">
		<label for="password">Password</label>
		<input type="password" name="password" id="password" placeholder="your password">
	</div>
	<input type="hidden" name="action" value="login">
	<button type="submit" class="btn-logreg">Submit</button>

</form>