<nav class="nav-menu-burger">
	<div class="open-menu-burger" id="open-menu-burger">
		<span></span>
		<span></span>
		<span></span>
	</div>
	<ul class="menu-burger" id="menu-burger">
		<form method="POST" action="index.php?page=product_admin">
			<input type="hidden" name="action" value="edit">
			<input type="hidden" name="id_product" value="<?=$id_product?>">
			<input class="menu-burger-button" type="submit" value="Edit">
		</form>
		<form method="POST" action="index.php?page=product_admin">
			<input type="hidden" name="action" value="delete">
			<input type="hidden" name="id_product" value="<?=$id_product?>">
			<input class="menu-burger-button" type="submit" value="Delete">
		</form>
	</ul>
</nav>