<h1>Espace Admin</h1>
<nav>
	<ul>
		<li><a href="index.php?page=edit_contact">Modifier mes informations</a></li>
		<li><a href="index.php?page=feedback">Administration des avis</a></li>
		<li><a href="index.php?page=cat_admin">Administration des catégories</a></li>
		<li><a href="index.php?page=product_admin">Administration des produits</a></li>
		<li><a href="index.php?page=cart">Administration des paniers</a></li>
	</ul>
</nav>