<h1>My Account</h1>
<nav>
	<ul>
		<li><a href="index.php?page=feedback">Feedback</a></li>
		<li><a href="index.php?page=display_cat">Category</a></li>
		<li><a href="index.php?page=product_admin">Products</a></li>
		<li><a href="index.php?page=cart">Cart</a></li>
		<li><a href="index.php?page=edit_contact">Edit Profile</a></li>
		<li><a href="index.php?page=change_password">Change Password</a></li>
	</ul>
</nav>