<div class="account text-center">
	<h1>My Account</h1>

	<nav class="nav-account clearfix">
		<div class="account-menu">
			<div class="account-option-padding">
				<div class="account-option"><a href="index.php?page=edit_contact">Edit Profile</a></div>
			</div>
			<div class="account-option-padding">
				<div class="account-option"><a href="index.php?page=change_password">Change Password</a></div>
			</div>
			<div class="account-option-padding">
				<div class="account-option"><a href="index.php?page=cart">My Carts</a></div>
			</div>
			
		</div>

		<div class="account-menu">
			<div class="account-option-padding">
				<div class="account-option"><a href="index.php?page=feedback">My Feedbacks</a></div>
			</div>
			<div class="account-option-padding">
				<div class="account-option"><a href="index.php?page=edit_contact?action=delete">Delete My Account</a></div>
			</div>
			<div class="account-option-padding">
				<div class="account-option"><a href="index.php?page=address">My Address</a></div>	
		</div>
	</nav>
</div>
