<div class="text-center clearfix">
	<h1 class="title" >Welcome to your profile</h1>

	<nav class="nav-account clearfix">
		<div class="account-menu">

			<div class="account-option-padding">
				<div class="account-option">
					<a href="#" data-target="change_password" data-element="#change_password">Change password</a>
				</div>
			</div>

			<div class="account-option-padding">
				<div class="account-option">
					<a href="#" data-target="edit_contact" data-element="#edit_contact">Edit profile</a>
				</div>
			</div>

			<div class="account-option-padding">
				<div class="account-option">
					<a href="#" data-target="address" data-element="#edit_address">Edit address</a>
				</div>	
			</div>

			<div class="account-option-padding">
				<div class="account-option">
					<a href="#" data-target="display_carts" data-element="#cart_user">My Carts</a>
				</div>
			</div>

			<div class="account-option-padding">
				<div class="account-option">
					<a href="#" data-target="feedback" data-element="#feedback_user">My Feedbacks</a>
				</div>
			</div>

			<div class="account-option-padding delete-profile">
				<form class="delete-button" method="POST">
					<input type="hidden" name="action" value="delete">
					<input type="submit" value="Delete my Account">
				</form>
			</div>
		</div>
	</nav>

	<!--Ajax-->
	<div class="ajax">
		<div id="ajax_profile_user">
			<!--Affichage des pages en Ajax ici-->
		</div>

		<script>
			$(document).ready(function(){

				$(".account-option a").click(function(event){
					event.preventDefault();
					/* event.preventDefault(); ->Permet d'annuler le comportement du lien "href" pour ne garder que le clic par defaut */
					var target = $(this).data("target");
					var element = $(this).data("element");
					$("#ajax_profile_user").load("index.php?page="+target+" "+element);
				});
			});
		</script>
	</div>
</div>
