<div class="account text-center clearfix">
	<h1 class="title">Welcome to your profile</h1>

	<nav class="nav-account clearfix">
		<div class="account-menu">
			<div class="account-option-padding">
				<div class="account-option">
					<a href="#" data-target="change_password">Change My Password</a>
				</div>
			</div>

			<div class="account-option-padding">
				<div class="account-option">
					<a href="#" data-target="edit_contact">Edit My Profile</a>
				</div>
			</div>

			<div class="account-option-padding">
				<div class="account-option">
					<a href="#" data-target="edit_address">Edit My Address</a>
				</div>
			</div>

			<div class="account-option-padding">
				<div class="account-option">
					<a href="#" data-target="cat_admin">Edit Category</a>
				</div>
			</div>

			<div class="account-option-padding">
				<div class="account-option">
					<a href="#" data-target="product_admin">Edit Products</a>
				</div>
			</div>

			<div class="account-option-padding">
				<div class="account-option">
					<a href="#" data-target="feedback_admin">Moderate Feedback</a>
				</div>
			</div>

			<div class="account-option-padding">
				<div class="account-option">
					<a href="#" data-target="display_carts_admin">Moderate Cart</a>
				</div>
			</div>
		</div>
	</nav>

	<!--Ajax-->
	<div class="ajax">
		<div id="ajax_profile_admin">
			<!--Affichage des pages en Ajax ici-->
		</div>

		<script>
			$(document).ready(function(){

				$(".account-option a").click(function(event){
					event.preventDefault();
					/* event.preventDefault(); ->Permet d'annuler le comportement du lien "href" pour ne garder que le clic par defaut */
					var target = $(this).data("target");
					$("#ajax_profile_admin").load("index.php?page="+target+" #"+target);
				});
			});
		</script>
	</div>
</div>