<h1>Register</h1>

<form method = "POST" class = "form-logreg">

	<div class = "form-reg">
		<label for="login">Login</label>
		<input type="login" name="login" id="login" placeholder="specify a login">
	</div>

	<div class = "form-reg">
		<label for="firstname">Firstname</label>
		<input type="firstname" name="firstname" id="firstname" placeholder="your firstname">
	</div>

	<div class = "form-reg">
		<label for="lastname">Lastname</label>
		<input type="lastname" name="lastname" id="lastname" placeholder="your lastname">
	</div>

	<div class = "form-reg">
		<label for="email">Email address</label>
		<input type="email" name="email" id="email" placeholder="your email">
	</div>

	<div class = "form-reg">
		<label for="email">Confirm Email</label>
		<input type="email" name="confirmEmail" id="confirmEmail">
	</div>

	<div class = "form-reg">
		<label for="password">Password</label>
		<input type="password" name="password" id="password" placeholder="specify a password">
	</div>

	<div class = "form-reg">
		<label for="password">Confirm Password</label>
		<input type="password" name="confirmPassword" id="confirmPassword">
	</div>

	<div class = "form-reg">
		<label for="birth_date">Birth Date</label>
		<input type="date" name="birth_date" id="birth_date" placeholder="enter your birth_date">
	</div>

	<div class = "form-reg">
		<label for="phone">Phone</label>
		<input type="phone" name="phone" id="phone" placeholder="specify a phone">
	</div>

	<div class = "form-reg">
		<input type="radio" name="sex" value="M" id="men" checked /> <label for="men">Men</label>
		<input type="radio" name="sex" value="W" id="women" /> <label for="women">Women</label>
	</div>
	<input type="hidden" name="action" value="register">
	<button type="submit" class="btn-logreg">Submit</button>

</form>