<div class="container">
	<form method="GET">
		<i class="fa fa-search"></i>
		<input type="search" placeholder="search" name="search" id="search" />
	</form>

	<div id="results">
	<!-- Résultat de la barre de recherche -->	
	</div>
</div>

<script>
	$(document).ready(function(){
		$("form").keyup(function(){
			var $form = $(this),
				search = $form.find("input[name='search']").val();

			$("#results").load("index.php?page=search_result&ajax&search="+search);
		});
	});
</script>